controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
    path: /home
    controller: App\Controller\HomeController::home

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_subject:
    path: /subject
    controller: App\Controller\SubjectController::subject

app_basket:
    path: /basket
    controller: App\Controller\BasketController::basket

app_movies:
    path: /movies
    controller: App\Controller\MoviesController::movies